version: '3'

services:
  fake-gcs:
    image: fsouza/fake-gcs-server
    ports:
      - "4443:4443"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4443/storage/v1/b"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: -scheme http -public-host localhost:4443