// generated by `sqlx migrate build-script`
fn main() -> shadow_rs::SdResult<()> {
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=migrations");
    shadow_rs::new()
}
