apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: litestream-sandbox
  namespace: '93254674393'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 513.0.0
        run.googleapis.com/cpu-throttling: 'true'
        run.googleapis.com/execution-environment: gen1
        run.googleapis.com/startup-cpu-boost: 'false'
      labels:
        client.knative.dev/nonce: exjsqulwbw
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 128
      containers:
      - image: asia-northeast1-docker.pkg.dev/duxca-298210/cloud-run-source-deploy/litestream-sandbox:latest
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: '1'
            memory: 256Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: 93254674393-compute@developer.gserviceaccount.com
      timeoutSeconds: 3

